export default {
    login: "/login",
    fetchUser: "/fetch/user",
    fetchRecommendRoles: "/getRecommendRoles",
    fetchRecommendCourses: "/getRecommendCourses",
    fetchHotRoles: "/getHotRoles",
    fetchHotCourses: "/getHotCourses",
    fetchTeacherDetail: "/getTeacherDetail",
    fetchStudioInfo: "/getStudioInfo",
    fetchStudioHomeData: "/getStudioHomeData",
    fetchStudioCourses: "/getStudioCourses",
    fetchStudioTeachers: "/getStudioTeachers",
    fetchStudioMedias: "/getStudioMedias",
    fetchCourseDetail: "/getCourseDetail",
    fetchHotSearchCats: "/getHotSearchCats",
    fetchFindLists: "/getFindLists",
    fetchSuggestion: "/getSuggestion",
    fetchKindergarten: "/getMobileKindInfo",
    postLooking: "/looking"
};
